### ISSUE TITLE
Signals instead of methods

### ISSUE THREAD

**Issue by ThePat02** [Promptineer/MusicManager#1]
Is there a specific reason behind the design decision of having the features be signals instead of methods?

**Comment by skulltrick** [comment]
Primarily for simplicity, consistency, and flexibility. I suppose a mixture of functions and signals does seem more intuitive though.

I felt that doing everything signal based gives more freedom for out-of-the-box integrations. For example, if you wanted a script to know immediately when you play a song to do something, all you need to do is hookup the existing signal from MusicManager to a function in your new script.

```gdscript
func _ready() -> void:
	MusicManager.play_song.connect(_on_play_song)


func _on_play_song(song: MusicTrack, _is_looping: bool, _is_fading: bool, _fade_time: float):
	print("Now playing: " + song.name)
```

It may be a bit overkill using signals for everything, it's really just for maximum flexibility.

**Comment by ThePat02** [comment]
I am just bit confused about your approach. It works and is totally reasonable, but why not like this:

```gdscript
signal song_played(song, is_looping .... etc)

func play_song(song, ...)
  # Do something
 song_played.emit()
```

The main positive about this would be the way of documentation using docstrings and consistency with the Godot class design.

**Comment by skulltrick** [comment]
> I am just bit confused about your approach. It works and is totally reasonable, but why not like this:
> 
> ```gdscript
> signal song_played(song, is_looping .... etc)
> 
> func play_song(song, ...)
>   # Do something
>  song_played.emit()
> ```
> 
> The main positive about this would be the way of documentation using docstrings and consistency with the Godot class design.

You know, you honestly do raise a valid point here. Perhaps I should convert most of the signals into methods. I guess I may have been a bit blindsided by the novelty of the plugin being "signals only".

I genuinely appreciate the insight and feedback! Thank you.

**Comment by ThePat02** [comment]
> You know, you honestly do raise a valid point here.

If it works, it isn't stupid. I think that using signals for actually doing something can be misleading from an user standpoint. Signals should only be used for alerting others that something happened. Luckily it shouldn't be to hard to convert your code tho!
